# Generated by Django 3.1 on 2020-08-06 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('avatar_url', models.CharField(max_length=2048)),
                ('whatsapp', models.IntegerField()),
                ('bio', models.CharField(max_length=500)),
                ('subject', models.IntegerField()),
                ('subject_name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.IntegerField()),
                ('week_day_name', models.CharField(max_length=20)),
                ('start', models.CharField(max_length=5)),
                ('end', models.CharField(max_length=5)),
                ('start_seconds', models.IntegerField()),
                ('end_seconds', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='server.teacher')),
            ],
        ),
    ]
