# Generated by Django 3.1 on 2020-08-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('avatar_url', models.CharField(max_length=2048)),
                ('whatsapp', models.IntegerField(max_length=12)),
                ('bio', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=50)),
                ('cost', models.IntegerField(max_length=3)),
            ],
        ),
    ]
