# Generated by Django 3.1 on 2020-08-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='whatsapp',
            field=models.IntegerField(),
        ),
    ]
